#!/usr/bin/env bash
#This script displays information about subdomains

function get_record_info() {
  local domain=$1
  local subdomain=$2
  local record
  local record_type
  local destination

  
  record=$(dig +short "$subdomain.$domain")
  record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
  destination=$(echo "$record" | awk '{print $1}')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1

# Check if subdomain argument is provided
if [ -n "$2" ]
then
  subdomain=$2
  get_record_info "$domain" "$subdomain"
else
  get_record_info "$domain" www
  get_record_info "$domain" lb-01
  get_record_info "$domain" web-01
  get_record_info "$domain" web-02
fi

