#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”
STRING="Hello World!"
REDIRECTRULE="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECTRULE" "$FILE"
service nginx restart
