#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
TEXT="Hello World!"
REDIRECTRULE="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"
ERRORTEXT="Ceci n'est pas une page\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\tinternal;\n\t\troot /usr/share/nginx/html;\n\t}\n"
apt-get -y update
apt-get -y install nginx
sudo echo "$TEXT" > /var/www/html/index.nginx-debian.html
sed -i "40i\ $REDIRECTRULE" "$FILE"
echo "$ERRORTEXT" > "$ERRORFILE"
sed -i "40i\ $ERRORREDIRECT" "$FILE"
service nginx restart
