#!/usr/bin/env bash
# This script configures a web server to return a custom header response
TEXT="Hello World!"
REDIRECTRULE="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"
ERRORTEXT="Ceci n'est pas une page\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\tinternal;\n\t\troot /usr/share/nginx/html;\n\t}\n"
HEADER="\n\tadd_header X-Served-By $HOSTNAME;\n"

apt-get -y update
apt-get -y install nginx
sudo echo "$TEXT" > /var/www/html/index.nginx-debian.html
sed -i "40i\ $REDIRECTRULE" "$FILE"
echo "$ERRORTEXT" > "$ERRORFILE"
sed -i "44i\ $ERRORREDIRECT" "$FILE"
sed -i "50i\ $HEADER" "$FILE"
service nginx restart
