#!/usr/bin/env bash
# This script configures HAproxy in a load balancer
apt-get -y update 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 138384-web-01 100.26.17.152:80 check\n\tserver 138384-web-02 54.89.109.11:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
