#!/usr/bin/env bash
# This script configures HAproxy in a load balancer
apt-get -y update 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_original.cfg
echo "ENABLED=1" >> /etc/default/haproxy
echo -e 'global\n\tlog /dev/log    local0\n\tlog /dev/log    local1 notice\n\tchroot /var/lib/haproxy\n\tstats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners\n\tstats timeout 30s\n\tuser haproxy\n\tgroup haproxy\n\tdaemon\n\ndefaults\n\tlog     global\n\tmode    http\n\toption  httplog\n\toption  dontlognull\n\ttimeout connect 5000\n\ttimeout client  50000\n\ttimeout server  50000\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend http_backend\n\nbackend http_backend\n\tbalance roundrobin\n\tserver 138384-web-01 35.153.83.147:80 check\n\tserver 138384-web-02 52.201.158.242:80 check' > /etc/haproxy/haproxy.cfg
service haproxy restart
