#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep of 2
# seconds within each iteration, and displays "I am invincible!!!" whenever a
# SIGTERM is received

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
