#!/usr/bin/env bash
# This script prints out `Best School` 10 times and prints out `Hi` on the 9th iteration

i=0
while (( i<10 ));
do
	echo "Best School"
	if (( i==8  ))
	then
		echo "Hi"
	fi
	(( i++ ))
done
